/// Flutter icons DotIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DotIcon
///      fonts:
///       - asset: fonts/DotIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class DotIcon {
  DotIcon._();

  static const _kFontFam = 'DotIcon';
  static const String? _kFontPkg = null;

  static const IconData more_dot = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
