/// Flutter icons MicIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MicIcon
///      fonts:
///       - asset: fonts/MicIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MicIcon {
  MicIcon._();

  static const _kFontFam = 'MicIcon';
  static const String? _kFontPkg = null;

  static const IconData mic = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
